name = "daveslinkshare"
main = "src/index.js"
compatibility_date = "2025-01-01"

[build]
command = "npm run build"

# Cloudflare D1 Database Configuration
# Run: npx wrangler d1 create daves-links-db
# Then replace the database_id below with the actual ID from the command output
[[d1_databases]]
binding = "DB"
database_name = "daves-links-db"
database_id = "d10d8b73-a101-4a15-8584-662ed7091d5e"

[vars]
NODE_ENV = "production"
JWT_SECRET = "5b452b847b8dd1d2b68af11b176dba87aef2753d59118b30dcab0a4853e48979b2590bfebce52071807ba666d303acb86b17ee0e9256e35082289cf0e420545a"

